### ISSUE TITLE
Speaker/iPhone both options don't show up

### ISSUE THREAD

**Issue by chaawlaapooja** [dylancom/react-native-airplay-cast#2]
![image](https://user-images.githubusercontent.com/26603297/116793747-3d258080-aae6-11eb-8fd5-203692657396.png)

I do not see both speaker and iPhone option. I have implemented airplay button as shown in documentation. What could be the reason?

**Comment by dylancom** [comment]
@chaawlaapooja did you try it on a real device?

**Comment by chaawlaapooja** [comment]
@dylancom yes, the screenshot is taken on real device

**Comment by dylancom** [comment]
@chaawlaapooja You're sure that your devices are connected to the same WiFi network? Just tested and it shows Speakers & TV's.
